/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "SimpleAssembly",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleAssembly__factory>;
    getContractFactory(
      name: "StandaloneVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StandaloneVerifier__factory>;
    getContractFactory(
      name: "TestLibBlockHeader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestLibBlockHeader__factory>;
    getContractFactory(
      name: "TestnetVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestnetVerifier__factory>;
    getContractFactory(
      name: "LibBlockHeaderDecoder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibBlockHeaderDecoder__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;

    getContractAt(
      name: "SimpleAssembly",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleAssembly>;
    getContractAt(
      name: "StandaloneVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.StandaloneVerifier>;
    getContractAt(
      name: "TestLibBlockHeader",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestLibBlockHeader>;
    getContractAt(
      name: "TestnetVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestnetVerifier>;
    getContractAt(
      name: "LibBlockHeaderDecoder",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibBlockHeaderDecoder>;
    getContractAt(
      name: "Verifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
