/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface SimpleAssemblyInterface extends utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "simpleAssemblyCalldataLoad(bytes)": FunctionFragment;
    "simpleAssemblyConditionalRevert(bytes)": FunctionFragment;
    "simpleAssemblyReturn()": FunctionFragment;
    "simpleAssemblyRevert()": FunctionFragment;
    "simpleAssemblyRevertWithReturn()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "owner"
      | "simpleAssemblyCalldataLoad"
      | "simpleAssemblyConditionalRevert"
      | "simpleAssemblyReturn"
      | "simpleAssemblyRevert"
      | "simpleAssemblyRevertWithReturn"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "simpleAssemblyCalldataLoad",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "simpleAssemblyConditionalRevert",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "simpleAssemblyReturn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "simpleAssemblyRevert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "simpleAssemblyRevertWithReturn",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "simpleAssemblyCalldataLoad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simpleAssemblyConditionalRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simpleAssemblyReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simpleAssemblyRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simpleAssemblyRevertWithReturn",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SimpleAssembly extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleAssemblyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    owner(overrides?: CallOverrides): Promise<[string]>;

    simpleAssemblyCalldataLoad(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    simpleAssemblyConditionalRevert(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    simpleAssemblyReturn(overrides?: CallOverrides): Promise<[void]>;

    simpleAssemblyRevert(overrides?: CallOverrides): Promise<[void]>;

    simpleAssemblyRevertWithReturn(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  simpleAssemblyCalldataLoad(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  simpleAssemblyConditionalRevert(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  simpleAssemblyReturn(overrides?: CallOverrides): Promise<void>;

  simpleAssemblyRevert(overrides?: CallOverrides): Promise<void>;

  simpleAssemblyRevertWithReturn(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    simpleAssemblyCalldataLoad(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simpleAssemblyConditionalRevert(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simpleAssemblyReturn(overrides?: CallOverrides): Promise<void>;

    simpleAssemblyRevert(overrides?: CallOverrides): Promise<void>;

    simpleAssemblyRevertWithReturn(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    simpleAssemblyCalldataLoad(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simpleAssemblyConditionalRevert(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simpleAssemblyReturn(overrides?: CallOverrides): Promise<BigNumber>;

    simpleAssemblyRevert(overrides?: CallOverrides): Promise<BigNumber>;

    simpleAssemblyRevertWithReturn(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    simpleAssemblyCalldataLoad(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simpleAssemblyConditionalRevert(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simpleAssemblyReturn(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simpleAssemblyRevert(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simpleAssemblyRevertWithReturn(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
